package interfaz.notificaciones;

import baseGeneral.ErrorEntity;
import baseGeneral.JTextMascara;
import bl.catalogos.AutoridadesNotificacionesBl;
import entitys.SesionEntity;
import entitys.AutoridadNotificacionEntity;
import java.awt.event.KeyEvent;

/**
 *
 * @author mavg
 */
public class AgregarAutoridad extends javax.swing.JDialog {

    AutoridadNotificacionEntity auto;
    javax.swing.JFrame parent;
    SesionEntity sesion;
    AutoridadesNotificacionesBl bl = new AutoridadesNotificacionesBl();
    
    /**
     * Creates new form AgregarPretension
     * @param parent
     * @param modal
     * @param auto
     * @param sesion
     */
    public AgregarAutoridad(javax.swing.JFrame parent, boolean modal, AutoridadNotificacionEntity auto, SesionEntity sesion) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        this.auto = auto;
        this.sesion = sesion;
        txtNombre.setDocument(new JTextMascara(300,true,"todo"));
    }
    
    private void botonF2(){
        if(txtNombre.getText().length()==0){
            javax.swing.JOptionPane.showInternalMessageDialog(this,"El campo Nombre es obligatorio", "Alerta", 2);
        }else{
            auto.setNombre(txtNombre.getText());
            ErrorEntity error = bl.saveAutoridad(auto,sesion);
            if(!error.getError()){
                auto = bl.getAutoNombre(txtNombre.getText());
                setVisible(false);
            }else{
                javax.swing.JOptionPane.showInternalMessageDialog(this,error.getTipo(), "Error", 0);
            }
        }
    }
    
    private void botonEsc(){
        auto.setId_autoridad("-1");
        setVisible(false);
    }
    
    private void eventosBotones(java.awt.event.KeyEvent evt){
        if(evt.getKeyCode()==KeyEvent.VK_F2){
            botonF2();
        }else if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            botonEsc();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Nombre de la Nueva Autoridad");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 260, 30);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        jPanel1.add(txtNombre);
        txtNombre.setBounds(10, 40, 580, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("F2 - Guardar");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 90, 130, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Esc - Cancelar");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 90, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        botonF2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        botonEsc();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        eventosBotones(evt);
    }//GEN-LAST:event_txtNombreKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
