package interfaz.principal;

import base.RelojModeloSwing;
import base.RelojVisual;
import interfaz.operaciones.*;
import interfaz.utilidades.*;
import interfaz.expedientes.*;
import baseGeneral.ImageDesktopPane;
import baseGeneral.Utilerias;
import baseSistema.Utilidades;
import entitys.SesionEntity;
import interfaz.catalogos.*;
import interfaz.notificaciones.*;
import interfaz.promociones.*;
import interfaz.reportes.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.Box;


/**
 *
 * @author mavg
 */
public class MDI extends javax.swing.JFrame {

    SesionEntity sesion;
    Utilerias u = new Utilerias();
    Utilidades uti = new Utilidades();
    javax.swing.JComponent []menusG;
    
    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
    }

    public MDI(SesionEntity sesion) {
        this.sesion = sesion;
        initComponents();
        inicio();
        pantallas();
        cargarImagen(panelPrincipal);
        RelojModeloSwing modelo = new RelojModeloSwing();
        RelojVisual visual = new RelojVisual(modelo);
        visual.setFormat(new SimpleDateFormat(" hh:mm:ss aaa "));
        Reloj.add(visual);
    }
    
    public final void cargarImagenLabel1(){
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        try{
            //System.out.println("src/imagenes/Logo" + d.width + "x" + d.height + ".jpg");
            //BufferedImage image = ImageIO.read(new File("src/imagenes/Logo" + d.width + "x" + d.height + ".jpg"));
            //panel.setBorder(new ImageDesktopPane(image));
            //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("src/imagenes/Logo" + d.width + "x" + d.height + ".jpg")));
            
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    
    public final void cargarImagen(javax.swing.JDesktopPane panel){
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        try{
            //System.out.println("src/imagenes/Logo" + d.width + "x" + d.height + ".jpg");
            BufferedImage image = ImageIO.read(new File("src/imagenes/Logo" + d.width + "x" + d.height + ".jpg"));
            panel.setBorder(new ImageDesktopPane(image));
            
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    private void inicio(){
        javax.swing.JComponent []menus ={
            menuPrincipal,
            menu01,menu01_01,menu01_02,menu01_03,menu01_04,
            menu02,
            menu03,
            menu04,
            menu05,
            menu06,
            menu07,menu07_01,menu07_02,menu07_03,menu07_04,menu07_05,menu07_06,
            menu08,
            menu09,
            menu11_04,
            menuCatalogos,menu11_01,menu11_02,menu11_03,menu11_04,menu11_05,menu11_06,menu11_07,menu11_08,menu11_09,menu11_10,
                menu11_11,menu11_12,menu11_13,menu11_14,menu11_15,menu11_16,menu11_17,
            menuReportes,menu12_01,menu12_02,menu12_03,menu12_04,menu12_05,menu12_06,menu12_07,menu12_08,menu12_09,menu12_10,menu12_11,menu12_12,
            menuUtilerias,menu13_01,menu13_02,menu13_03,menu13_04,menu13_05
        };
        menusG = menus;
    }
    
    private void pantallas(){
        String pan = sesion.getPantallas();
        for(int i=0; i<menusG.length; i++){
            if(menusG[i] instanceof javax.swing.JMenu){
                javax.swing.JMenu men = (javax.swing.JMenu)menusG[i];
                men.setVisible((pan.charAt(i)=='1'));
            }else if(menusG[i] instanceof javax.swing.JMenuItem){
                javax.swing.JMenuItem men = (javax.swing.JMenuItem)menusG[i];
                men.setVisible((pan.charAt(i)=='1'));
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JDesktopPane();
        Reloj = new javax.swing.JToolBar();
        menuBar = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        menuPrincipal = new javax.swing.JMenu();
        menu01 = new javax.swing.JMenu();
        menu01_01 = new javax.swing.JMenuItem();
        menu01_02 = new javax.swing.JMenuItem();
        menu01_03 = new javax.swing.JMenuItem();
        menu01_04 = new javax.swing.JMenuItem();
        menu02 = new javax.swing.JMenuItem();
        menu03 = new javax.swing.JMenuItem();
        menu04 = new javax.swing.JMenuItem();
        menu05 = new javax.swing.JMenuItem();
        menu06 = new javax.swing.JMenuItem();
        menu07 = new javax.swing.JMenu();
        menu07_01 = new javax.swing.JMenuItem();
        menu07_02 = new javax.swing.JMenuItem();
        menu07_03 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu07_04 = new javax.swing.JMenuItem();
        menu07_05 = new javax.swing.JMenuItem();
        menu07_06 = new javax.swing.JMenuItem();
        menu08 = new javax.swing.JMenuItem();
        menu09 = new javax.swing.JMenuItem();
        menuCatalogos = new javax.swing.JMenu();
        menu11_01 = new javax.swing.JMenuItem();
        menu11_02 = new javax.swing.JMenuItem();
        menu11_03 = new javax.swing.JMenuItem();
        menu11_04 = new javax.swing.JMenuItem();
        menu11_05 = new javax.swing.JMenuItem();
        menu11_06 = new javax.swing.JMenuItem();
        menu11_07 = new javax.swing.JMenuItem();
        menu11_08 = new javax.swing.JMenuItem();
        menu11_09 = new javax.swing.JMenuItem();
        menu11_10 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu11_11 = new javax.swing.JMenuItem();
        menu11_12 = new javax.swing.JMenuItem();
        menu11_13 = new javax.swing.JMenuItem();
        menu11_14 = new javax.swing.JMenuItem();
        menu11_15 = new javax.swing.JMenuItem();
        menu11_16 = new javax.swing.JMenuItem();
        menu11_17 = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menu12_01 = new javax.swing.JMenuItem();
        menu12_02 = new javax.swing.JMenuItem();
        menu12_03 = new javax.swing.JMenuItem();
        menu12_04 = new javax.swing.JMenuItem();
        menu12_05 = new javax.swing.JMenuItem();
        menu12_06 = new javax.swing.JMenuItem();
        menu12_07 = new javax.swing.JMenuItem();
        menu12_08 = new javax.swing.JMenuItem();
        menu12_09 = new javax.swing.JMenuItem();
        menu12_10 = new javax.swing.JMenuItem();
        menu12_11 = new javax.swing.JMenuItem();
        menu12_12 = new javax.swing.JMenuItem();
        menuUtilerias = new javax.swing.JMenu();
        menu13_01 = new javax.swing.JMenuItem();
        menu13_02 = new javax.swing.JMenuItem();
        menu13_03 = new javax.swing.JMenuItem();
        menu13_04 = new javax.swing.JMenuItem();
        menu13_05 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 748));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(240, 240, 240));

        Reloj.setFloatable(false);
        Reloj.setRollover(true);
        Reloj.setFocusable(false);

        panelPrincipal.setLayer(Reloj, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Reloj, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 682, Short.MAX_VALUE)
                .addComponent(Reloj, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuBar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuInicio.setMnemonic('f');
        menuInicio.setText("Inicio");
        menuInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        openMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Cerrar sesión");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        menuInicio.add(openMenuItem);

        exitMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menuInicio.add(exitMenuItem);

        menuBar.add(menuInicio);

        menuPrincipal.setMnemonic('e');
        menuPrincipal.setText("Principal");
        menuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalActionPerformed(evt);
            }
        });

        menu01.setText("Expedientes");
        menu01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menu01_01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu01_01.setText("Nuevo Expediente");
        menu01_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu01_01ActionPerformed(evt);
            }
        });
        menu01.add(menu01_01);

        menu01_02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu01_02.setText("Modificar Expediente");
        menu01_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu01_02ActionPerformed(evt);
            }
        });
        menu01.add(menu01_02);

        menu01_03.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu01_03.setText("Eliminar Expediente");
        menu01_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu01_03ActionPerformed(evt);
            }
        });
        menu01.add(menu01_03);

        menu01_04.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu01_04.setText("Ubicar Expediente");
        menu01_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu01_04ActionPerformed(evt);
            }
        });
        menu01.add(menu01_04);

        menuPrincipal.add(menu01);

        menu02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu02.setText("Registro de Promociones");
        menu02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu02ActionPerformed(evt);
            }
        });
        menuPrincipal.add(menu02);

        menu03.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu03.setText("Inicio de Trámites");
        menu03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu03ActionPerformed(evt);
            }
        });
        menuPrincipal.add(menu03);

        menu04.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu04.setText("Registro de Autos");
        menu04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu04ActionPerformed(evt);
            }
        });
        menuPrincipal.add(menu04);

        menu05.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu05.setText("Registro de Resoluciones de la Secretaría de Acuerdos");
        menu05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu05ActionPerformed(evt);
            }
        });
        menuPrincipal.add(menu05);

        menu06.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu06.setText("Registro de Sentencias - Resoluciones de Mesas de Trámite");
        menu06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu06ActionPerformed(evt);
            }
        });
        menuPrincipal.add(menu06);

        menu07.setText("Notificaciones");
        menu07.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menu07_01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu07_01.setText("Carga de Notificaciones");
        menu07_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu07_01ActionPerformed(evt);
            }
        });
        menu07.add(menu07_01);

        menu07_02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu07_02.setText("Descarga de Notificaciones");
        menu07_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu07_02ActionPerformed(evt);
            }
        });
        menu07.add(menu07_02);

        menu07_03.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu07_03.setText("Buscar y Eliminar Notificaciones");
        menu07_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu07_03ActionPerformed(evt);
            }
        });
        menu07.add(menu07_03);
        menu07.add(jSeparator2);

        menu07_04.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu07_04.setText("Carga Extra de Notificaciones");
        menu07_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu07_04ActionPerformed(evt);
            }
        });
        menu07.add(menu07_04);

        menu07_05.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu07_05.setText("Descarga Extra de Notificaciones");
        menu07_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu07_05ActionPerformed(evt);
            }
        });
        menu07.add(menu07_05);

        menu07_06.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu07_06.setText("Buscar y Eliminar Notificaciones Extra");
        menu07_06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu07_06ActionPerformed(evt);
            }
        });
        menu07.add(menu07_06);

        menuPrincipal.add(menu07);

        menu08.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu08.setText("Archivar Expedientes");
        menu08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu08ActionPerformed(evt);
            }
        });
        menuPrincipal.add(menu08);

        menu09.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu09.setText("Acumulación de Expedientes");
        menu09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu09ActionPerformed(evt);
            }
        });
        menuPrincipal.add(menu09);

        menuBar.add(menuPrincipal);

        menuCatalogos.setText("Catálogos");
        menuCatalogos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menu11_01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_01.setText("Actos Impugnados");
        menu11_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_01ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_01);

        menu11_02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_02.setText("Autoridades");
        menu11_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_02ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_02);

        menu11_03.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_03.setText("Autoridades de Notificaciones Extra");
        menu11_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_03ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_03);

        menu11_04.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_04.setText("Autorizados");
        menu11_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_04ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_04);

        menu11_05.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_05.setText("Destinos");
        menu11_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_05ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_05);

        menu11_06.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_06.setText("Municipios");
        menu11_06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_06ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_06);

        menu11_07.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_07.setText("Procedimientos");
        menu11_07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_07ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_07);

        menu11_08.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_08.setText("Sentidos de Ejecutoria");
        menu11_08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_08ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_08);

        menu11_09.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_09.setText("Supuestos");
        menu11_09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_09ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_09);

        menu11_10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_10.setText("Suspensiones");
        menu11_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_10ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_10);
        menuCatalogos.add(jSeparator1);

        menu11_11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_11.setText("Tipo de Ámparos");
        menu11_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_11ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_11);

        menu11_12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_12.setText("Tipo de Autoridades");
        menu11_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_12ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_12);

        menu11_13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_13.setText("Tipo de Autos");
        menu11_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_13ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_13);

        menu11_14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_14.setText("Tipo de Documentos");
        menu11_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_14ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_14);

        menu11_15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_15.setText("Tipo de Pretensiones");
        menu11_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_15ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_15);

        menu11_16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_16.setText("Tipo de Promociones");
        menu11_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_16ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_16);

        menu11_17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu11_17.setText("Tipo de Sentencias");
        menu11_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu11_17ActionPerformed(evt);
            }
        });
        menuCatalogos.add(menu11_17);

        menuBar.add(menuCatalogos);

        menuReportes.setText("Reportes");
        menuReportes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menu12_01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_01.setText("Listado de Reportes de Catálogo");
        menu12_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_01ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_01);

        menu12_02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_02.setText("Lista de Acuerdos");
        menu12_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_02ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_02);

        menu12_03.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_03.setText("Información de Expediente");
        menu12_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_03ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_03);

        menu12_04.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_04.setText("Reportes de Promociones");
        menu12_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_04ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_04);

        menu12_05.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_05.setText("Reportes de Autos");
        menu12_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_05ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_05);

        menu12_06.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_06.setText("Reportes de Resoluciones");
        menu12_06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_06ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_06);

        menu12_07.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_07.setText("Reportes de Sentencias");
        menu12_07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_07ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_07);

        menu12_08.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_08.setText("Estado Procesal");
        menu12_08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_08ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_08);

        menu12_09.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_09.setText("Reportes de Notificaciones");
        menu12_09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_09ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_09);

        menu12_10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_10.setText("Reportes Estadísticos");
        menu12_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_10ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_10);

        menu12_11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_11.setText("Reportes Estadísticos de Notificaciones");
        menu12_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_11ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_11);

        menu12_12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu12_12.setText("Reportes de Expedientes Acumulados");
        menu12_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu12_12ActionPerformed(evt);
            }
        });
        menuReportes.add(menu12_12);

        menuBar.add(menuReportes);

        menuUtilerias.setText("Utilerias");
        menuUtilerias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menu13_01.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu13_01.setText("Calendario Oficial");
        menu13_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu13_01ActionPerformed(evt);
            }
        });
        menuUtilerias.add(menu13_01);

        menu13_02.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu13_02.setText("Búsqueda de Personas");
        menu13_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu13_02ActionPerformed(evt);
            }
        });
        menuUtilerias.add(menu13_02);

        menu13_03.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu13_03.setText("Usuarios");
        menu13_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu13_03ActionPerformed(evt);
            }
        });
        menuUtilerias.add(menu13_03);

        menu13_04.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu13_04.setText("Respaldo de Base de Datos");
        menu13_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu13_04ActionPerformed(evt);
            }
        });
        menuUtilerias.add(menu13_04);

        menu13_05.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menu13_05.setText("Búsqueda de Autoridades");
        menu13_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu13_05ActionPerformed(evt);
            }
        });
        menuUtilerias.add(menu13_05);

        menuBar.add(menuUtilerias);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");
        helpMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        aboutMenuItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca de");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void menu13_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu13_01ActionPerformed
        u.muestraForm(new CalendarioOficial(sesion), panelPrincipal);
    }//GEN-LAST:event_menu13_01ActionPerformed

    private void menu11_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_05ActionPerformed
        u.muestraForm(new Destinos(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_05ActionPerformed

    private void menu11_08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_08ActionPerformed
        u.muestraForm(new SentidoEjecuciones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_08ActionPerformed

    private void menu11_09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_09ActionPerformed
        u.muestraForm(new Supuestos(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_09ActionPerformed

    private void menu11_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_14ActionPerformed
        u.muestraForm(new TipoDocumentosAsr(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_14ActionPerformed

    private void menu11_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_15ActionPerformed
        u.muestraForm(new TipoPretensiones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_15ActionPerformed

    private void menu11_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_10ActionPerformed
        u.muestraForm(new Suspensiones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_10ActionPerformed

    private void menu11_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_17ActionPerformed
        u.muestraForm(new TipoSentencias(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_17ActionPerformed

    private void menu11_06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_06ActionPerformed
        u.muestraForm(new Municipios(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_06ActionPerformed

    private void menu11_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_11ActionPerformed
        u.muestraForm(new TipoAmparos(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_11ActionPerformed

    private void menu11_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_12ActionPerformed
        u.muestraForm(new TipoAutoridades(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_12ActionPerformed

    private void menu11_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_16ActionPerformed
        u.muestraForm(new TipoPromociones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_16ActionPerformed

    private void menu11_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_02ActionPerformed
        u.muestraForm(new Autoridades(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_02ActionPerformed

    private void menu11_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_13ActionPerformed
        u.muestraForm(new Autos(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_13ActionPerformed

    private void menu11_07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_07ActionPerformed
        u.muestraForm(new Procedimientos(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_07ActionPerformed

    private void menu01_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu01_01ActionPerformed
        u.muestraForm(new Expediente(sesion), panelPrincipal);
    }//GEN-LAST:event_menu01_01ActionPerformed

    private void menu11_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_04ActionPerformed
        u.muestraForm(new Autorizados(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_04ActionPerformed

    private void menu01_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu01_02ActionPerformed
        u.muestraForm(new ExpedienteUpdate(sesion), panelPrincipal);
    }//GEN-LAST:event_menu01_02ActionPerformed

    private void menu01_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu01_03ActionPerformed
        u.muestraForm(new ExpedienteDelete(sesion), panelPrincipal);
    }//GEN-LAST:event_menu01_03ActionPerformed

    private void menu08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu08ActionPerformed
        u.muestraForm(new ArchivarExpedientes(sesion), panelPrincipal);
    }//GEN-LAST:event_menu08ActionPerformed

    private void menu09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu09ActionPerformed
        u.muestraForm(new AnexarExpedientes(sesion), panelPrincipal);
    }//GEN-LAST:event_menu09ActionPerformed

    private void menuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalActionPerformed
        
    }//GEN-LAST:event_menuPrincipalActionPerformed

    private void menu03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu03ActionPerformed
        u.muestraForm(new InicioTramite(sesion), panelPrincipal);
    }//GEN-LAST:event_menu03ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //System.out.println(uti.getFormatoFechaString());
    }//GEN-LAST:event_formComponentShown

    private void menu13_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu13_02ActionPerformed
        u.muestraForm(new BusquedaPersonas(sesion), panelPrincipal);
    }//GEN-LAST:event_menu13_02ActionPerformed

    private void menu12_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_01ActionPerformed
        u.muestraForm(new ListadoCatalogos(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_01ActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void menu11_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_01ActionPerformed
        u.muestraForm(new Actos(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_01ActionPerformed

    private void menu04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu04ActionPerformed
        u.muestraForm(new RegistroAutos(sesion), panelPrincipal);
    }//GEN-LAST:event_menu04ActionPerformed

    private void menu07_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu07_01ActionPerformed
        u.muestraForm(new CargaNotificaciones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu07_01ActionPerformed

    private void menu07_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu07_02ActionPerformed
        u.muestraForm(new DescargaNotificaciones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu07_02ActionPerformed

    private void menu11_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu11_03ActionPerformed
        u.muestraForm(new AutoridadesNotificaciones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu11_03ActionPerformed

    private void menu07_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu07_04ActionPerformed
        u.muestraForm(new CargaNotificacionesExtra(sesion), panelPrincipal);
    }//GEN-LAST:event_menu07_04ActionPerformed

    private void menu07_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu07_05ActionPerformed
        u.muestraForm(new DescargaNotificacionesExtra(sesion), panelPrincipal);
    }//GEN-LAST:event_menu07_05ActionPerformed

    private void menu07_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu07_03ActionPerformed
        u.muestraForm(new BorrarNotificaciones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu07_03ActionPerformed

    private void menu05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu05ActionPerformed
        u.muestraForm(new RegistroResoluciones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu05ActionPerformed

    private void menu06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu06ActionPerformed
        u.muestraForm(new RegistroSentencias(sesion), panelPrincipal);
    }//GEN-LAST:event_menu06ActionPerformed

    private void menu13_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu13_03ActionPerformed
        u.muestraForm(new Usuarios(sesion), panelPrincipal);
    }//GEN-LAST:event_menu13_03ActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        dispose();
        Main.inicioSesion.show();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void menu02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu02ActionPerformed
        u.muestraForm(new PromocionesUpdate(sesion), panelPrincipal);
    }//GEN-LAST:event_menu02ActionPerformed

    private void menu12_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_02ActionPerformed
        u.muestraForm(new ListadeAcuerdos(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_02ActionPerformed

    private void menu12_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_03ActionPerformed
        u.muestraForm(new infoExpediente(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_03ActionPerformed

    private void menu12_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_04ActionPerformed
        u.muestraForm(new ReportesPromociones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_04ActionPerformed

    private void menu12_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_05ActionPerformed
        u.muestraForm(new ReportesAutos(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_05ActionPerformed

    private void menu12_06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_06ActionPerformed
        u.muestraForm(new ReportesResoluciones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_06ActionPerformed

    private void menu12_07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_07ActionPerformed
        u.muestraForm(new ReportesSentencias(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_07ActionPerformed

    private void menu07_06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu07_06ActionPerformed
        u.muestraForm(new BorrarNotificacionesExtra(sesion), panelPrincipal);
    }//GEN-LAST:event_menu07_06ActionPerformed

    private void menu12_08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_08ActionPerformed
        u.muestraForm(new ReportesDinamicosAutos(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_08ActionPerformed

    private void menu12_09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_09ActionPerformed
        u.muestraForm(new ReportesNotificaciones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_09ActionPerformed

    private void menu12_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_10ActionPerformed
        u.muestraForm(new ListadoReportes(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_10ActionPerformed

    private void menu13_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu13_04ActionPerformed
        u.muestraForm(new RespaldarBase(sesion), panelPrincipal);
    }//GEN-LAST:event_menu13_04ActionPerformed

    private void menu12_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_11ActionPerformed
        u.muestraForm(new ListadoNotificaciones(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_11ActionPerformed

    private void menu12_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu12_12ActionPerformed
        u.muestraForm(new ReportesAcumulados(sesion), panelPrincipal);
    }//GEN-LAST:event_menu12_12ActionPerformed

    private void menu13_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu13_05ActionPerformed
        u.muestraForm(new BusquedaAutoridades(sesion), panelPrincipal);
    }//GEN-LAST:event_menu13_05ActionPerformed

    private void menu01_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu01_04ActionPerformed
        u.muestraForm(new ExpedienteUbicacion(sesion), panelPrincipal);
    }//GEN-LAST:event_menu01_04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar Reloj;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menu01;
    private javax.swing.JMenuItem menu01_01;
    private javax.swing.JMenuItem menu01_02;
    private javax.swing.JMenuItem menu01_03;
    private javax.swing.JMenuItem menu01_04;
    private javax.swing.JMenuItem menu02;
    private javax.swing.JMenuItem menu03;
    private javax.swing.JMenuItem menu04;
    private javax.swing.JMenuItem menu05;
    private javax.swing.JMenuItem menu06;
    private javax.swing.JMenu menu07;
    private javax.swing.JMenuItem menu07_01;
    private javax.swing.JMenuItem menu07_02;
    private javax.swing.JMenuItem menu07_03;
    private javax.swing.JMenuItem menu07_04;
    private javax.swing.JMenuItem menu07_05;
    private javax.swing.JMenuItem menu07_06;
    private javax.swing.JMenuItem menu08;
    private javax.swing.JMenuItem menu09;
    private javax.swing.JMenuItem menu11_01;
    private javax.swing.JMenuItem menu11_02;
    private javax.swing.JMenuItem menu11_03;
    private javax.swing.JMenuItem menu11_04;
    private javax.swing.JMenuItem menu11_05;
    private javax.swing.JMenuItem menu11_06;
    private javax.swing.JMenuItem menu11_07;
    private javax.swing.JMenuItem menu11_08;
    private javax.swing.JMenuItem menu11_09;
    private javax.swing.JMenuItem menu11_10;
    private javax.swing.JMenuItem menu11_11;
    private javax.swing.JMenuItem menu11_12;
    private javax.swing.JMenuItem menu11_13;
    private javax.swing.JMenuItem menu11_14;
    private javax.swing.JMenuItem menu11_15;
    private javax.swing.JMenuItem menu11_16;
    private javax.swing.JMenuItem menu11_17;
    private javax.swing.JMenuItem menu12_01;
    private javax.swing.JMenuItem menu12_02;
    private javax.swing.JMenuItem menu12_03;
    private javax.swing.JMenuItem menu12_04;
    private javax.swing.JMenuItem menu12_05;
    private javax.swing.JMenuItem menu12_06;
    private javax.swing.JMenuItem menu12_07;
    private javax.swing.JMenuItem menu12_08;
    private javax.swing.JMenuItem menu12_09;
    private javax.swing.JMenuItem menu12_10;
    private javax.swing.JMenuItem menu12_11;
    private javax.swing.JMenuItem menu12_12;
    private javax.swing.JMenuItem menu13_01;
    private javax.swing.JMenuItem menu13_02;
    private javax.swing.JMenuItem menu13_03;
    private javax.swing.JMenuItem menu13_04;
    private javax.swing.JMenuItem menu13_05;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCatalogos;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUtilerias;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JDesktopPane panelPrincipal;
    // End of variables declaration//GEN-END:variables

}
