package interfaz.operaciones;

import baseGeneral.ErrorEntity;
import baseGeneral.JTextMascara;
import bl.catalogos.AutosBl;
import entitys.SesionEntity;
import entitys.AutoEntity;
import java.awt.event.KeyEvent;

/**
 *
 * @author mavg
 */
public class AgregarAuto extends javax.swing.JDialog {

    AutoEntity auto;
    javax.swing.JFrame parent;
    SesionEntity sesion;
    AutosBl bl = new AutosBl();
    
    /**
     * Creates new form AgregarPretension
     * @param parent
     * @param modal
     * @param auto
     * @param sesion
     */
    public AgregarAuto(javax.swing.JFrame parent, boolean modal, AutoEntity auto, SesionEntity sesion) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        this.auto = auto;
        this.sesion = sesion;
        txtNombre.setDocument(new JTextMascara(29,true,"todo"));
    }
    
    private void botonF2(){
        if(txtNombre.getText().length()==0){
            javax.swing.JOptionPane.showInternalMessageDialog(this,"El campo Nombre es obligatorio", "Alerta", 2);
        }else{
            auto.setNombre(txtNombre.getText());
            if(rbtnMesa.isSelected()){
                auto.setTipo(true);
            }else{
                auto.setTipo(false);
            }
            ErrorEntity error = bl.saveAuto(auto,sesion);
            if(!error.getError()){
                auto = bl.getAutoNombre(txtNombre.getText());
                setVisible(false);
            }else{
                javax.swing.JOptionPane.showInternalMessageDialog(this,error.getTipo(), "Error", 0);
            }
        }
    }
    
    private void botonEsc(){
        auto.setId_tipo_auto("-1");
        setVisible(false);
    }
    
    private void eventosBotones(java.awt.event.KeyEvent evt){
        if(evt.getKeyCode()==KeyEvent.VK_F2){
            botonF2();
        }else if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
            botonEsc();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rbtnMesa = new javax.swing.JRadioButton();
        rbtnSecre = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Nombre del Nuevo Auto");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 260, 30);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        jPanel1.add(txtNombre);
        txtNombre.setBounds(10, 40, 400, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("F2 - Guardar");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 160, 130, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Esc - Cancelar");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(280, 160, 130, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Auto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        buttonGroup1.add(rbtnMesa);
        rbtnMesa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtnMesa.setSelected(true);
        rbtnMesa.setText("Mesas de Trámite");

        buttonGroup1.add(rbtnSecre);
        rbtnSecre.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtnSecre.setText("Secretaría de Acuerdos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(rbtnSecre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMesa)
                    .addComponent(rbtnSecre))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 80, 400, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        botonF2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        botonEsc();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        eventosBotones(evt);
    }//GEN-LAST:event_txtNombreKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbtnMesa;
    private javax.swing.JRadioButton rbtnSecre;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
